OLL_FORMULAS.push(
  ollEntry(1,  'Dot 1', 'Dot', "(R U2') (R2' F R F') U2' (R' F R F')", 3),
  ollEntry(2,  'Dot 2', 'Dot', "F (R U R' U') F' f (R U R' U') f'", 3),
  ollEntry(3,  'Dot 3', 'Dot', "f (R U R' U') f' U' F (R U R' U') F'", 3),
  ollEntry(4,  'Dot 4', 'Dot', "f (R U R' U') f' U F (R U R' U') F'", 3),
  ollEntry(5,  'Square 1', 'Square', "(r' U2 R U R' U r)", 2),
  ollEntry(6,  'Square 2', 'Square', "(r U2 R' U' R U' r')", 2),
  ollEntry(7,  'Lightning 1', 'Lightning', "(r U R' U R U2 r')", 2),
  ollEntry(8,  'Lightning 2', 'Lightning', "(r' U' R U' R' U2 r)", 2),
  ollEntry(9,  'Fish (Kite) 1', 'Fish', "(R U R' U') R' F (R2 U R' U') F'", 3),
  ollEntry(10, 'Fish (Kite) 2', 'Fish', "(R U R' U) (R' F R F') (R U2 R')", 3),
  ollEntry(11, 'Lightning 3', 'Lightning', "r' (R2 U R' U R U2 R') U M'", 3),
  ollEntry(12, 'Lightning 4', 'Lightning', "M' (R' U' R U' R' U2 R) U' M", 3),
  ollEntry(13, 'Knight 1', 'Knight', "(r U' r') (U' r U r') y' (R' U R)", 3),
  ollEntry(14, 'Knight 2', 'Knight', "(R' F R) (U R' F' R) (F U' F')", 3),
  ollEntry(15, 'Knight 3', 'Knight', "(r' U' r) (R' U' R U) (r' U r)", 3),
  ollEntry(16, 'Knight 4', 'Knight', "(r U r') (R U R' U') (r U' r')", 3),
  ollEntry(17, 'Awkward 1', 'Awkward', "(R U R' U) (R' F R F') U2 (R' F R F')", 3),
  ollEntry(18, 'Awkward 2', 'Awkward', "F (R U R' U) y' (R' U2) (R' F R F')", 3),
  ollEntry(19, 'Awkward 3', 'Awkward', "M U (R U R' U') M' (R' F R F')", 3),
  ollEntry(20, 'Double Sune', 'Awkward', "M U (R U R' U') M2 (U R U' r')", 3),
  ollEntry(21, 'Cross / H', 'OCLL', "(R U2 R' U' R U R' U' R U' R')", 1, ["F (R U R' U')3 F'"], '双 Sune 合并'),
  ollEntry(22, 'Pi',        'OCLL', "R U2' R2' U' R2 U' R2' U2' R", 1, ["f (R U R' U') f' F (R U R' U') F'"]),
  ollEntry(23, 'Headlights','OCLL', "R2' D' R U2 R' D R U2 R", 1, ["R2 D (R' U2 R) D' (R' U2 R')"]),
  ollEntry(24, 'Bowtie',    'OCLL', "(r U R' U') (r' F R F')", 1),
  ollEntry(25, 'Bowtie 反 / Diagonal', 'OCLL', "F' (r U R' U') r' F R", 1, ["x' (R U R' D) (R U' R' D') x"]),
  ollEntry(26, 'Anti-Sune', 'OCLL', "(R U2 R' U' R U' R')", 1, ["L' U' L U' L' U2 L"], '左前角朝外'),
  ollEntry(27, 'Sune',      'OCLL', "(R U R' U R U2 R')", 1, ["L' U2 L U L' U L"], '最常用 OLL'),
  ollEntry(28, 'Block 1', 'Block', "(r U R' U') M (U R U' R')", 2),
  ollEntry(29, 'Block 2', 'Block', "(R U R' U') (R U' R') (F' U' F) (R U R')", 3),
  ollEntry(30, 'Block 3', 'Block', "F R' F (R2 U' R' U') (R U R') F2", 3)
);
