OLL_FORMULAS.push(
  ollEntry(31, 'P-shape 1', 'P-shape', "(R' U' F) (U R U' R') F' R", 2),
  ollEntry(32, 'P-shape 2', 'P-shape', "(S R U R' U') (R' F R f')", 2),
  ollEntry(33, 'T-shape 1', 'T-shape', "(R U R' U') (R' F R F')", 1, [], '熟悉 sexy + sledge 的组合'),
  ollEntry(34, 'C-shape 1', 'C-shape', "(R U R' U') B' (R' F R F') B", 2),
  ollEntry(35, 'Fish 3', 'Fish', "(R U2') (R2' F R F') (R U2' R')", 2),
  ollEntry(36, 'W-shape 1', 'W-shape', "(R' U' R U' R' U R U) l U' R' U x", 3),
  ollEntry(37, 'Fish 4 (Mounted)', 'Fish', "F (R U' R' U') (R U R' F')", 2),
  ollEntry(38, 'W-shape 2', 'W-shape', "(R U R' U) (R U' R' U') (R' F R F')", 2),
  ollEntry(39, 'Big Lightning 1', 'Lightning', "(L F') (L' U' L U) F U' L'", 3),
  ollEntry(40, 'Big Lightning 2', 'Lightning', "(R' F) (R U R' U') F' U R", 3),
  ollEntry(41, 'Awkward Fish 1', 'Awkward', "(R U R' U R U2' R') F (R U R' U') F'", 3),
  ollEntry(42, 'Awkward Fish 2', 'Awkward', "(R' U' R U' R' U2 R) F (R U R' U') F'", 3),
  ollEntry(43, 'P-shape 3', 'P-shape', "f' (L' U' L U) f", 2),
  ollEntry(44, 'P-shape 4', 'P-shape', "f (R U R' U') f'", 1, [], '镜像 OLL 45'),
  ollEntry(45, 'T-shape 2', 'T-shape', "F (R U R' U') F'", 1, [], '万能 OLL 之一'),
  ollEntry(46, 'L-shape (Seein\u2019 Headlights)', 'L-shape', "R' U' (R' F R F') U R", 2),
  ollEntry(47, 'L-shape 1', 'L-shape', "F' (L' U' L U) (L' U' L U) F", 2),
  ollEntry(48, 'L-shape 2', 'L-shape', "F (R U R' U') (R U R' U') F'", 2),
  ollEntry(49, 'L-shape 3', 'L-shape', "R B' R2 F R2 B R2 F' R", 3),
  ollEntry(50, 'L-shape 4', 'L-shape', "R' F R2 B' R2' F' R2 B R'", 3),
  ollEntry(51, 'Line 1', 'Line', "f (R U R' U') (R U R' U') f'", 2),
  ollEntry(52, 'Line 2', 'Line', "(R U R' U) R d' R U' R' F'", 2),
  ollEntry(53, 'L-shape 5', 'L-shape', "(r' U' R U' R' U R U' R' U2 r)", 3),
  ollEntry(54, 'L-shape 6', 'L-shape', "(r U R' U R U' R' U R U2' r')", 3),
  ollEntry(55, 'Line 3', 'Line', "R' F (R U R U' R2' F') R2 U' R' (U R U R')", 3),
  ollEntry(56, 'Line 4', 'Line', "(r U r') (U R U' R') (U R U' R') (r U' r')", 3),
  ollEntry(57, 'H (Edges Only)', 'OCLL', "(R U R' U') M' (U R U' r')", 1, ["(R U R' U R U' R') M' (U R U' r')"])
);
